- name: install fail2ban
  apt:
    name:
      - fail2ban
      - ipset
    state: present


- name: template /etc/fail2ban/fail2ban.local
  template:
    src: etc/fail2ban/fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 0640
  notify: restart fail2ban


- name: template /etc/fail2ban/jail.d/ configs
  template:
    src: etc/fail2ban/config_template.j2
    dest: "/etc/fail2ban/jail.d/{{ fail2ban_item['name'] }}.conf"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ fail2ban_jails }}"
  loop_control:
    loop_var: fail2ban_item
  notify: restart fail2ban

- name: template /etc/fail2ban/action.d/ configs
  template:
    src: etc/fail2ban/config_template.j2
    dest: "/etc/fail2ban/action.d/{{ fail2ban_item['name'] }}.conf"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ fail2ban_actions }}"
  loop_control:
    loop_var: fail2ban_item
  notify: restart fail2ban

- name: template /etc/fail2ban/filter.d/ configs
  template:
    src: etc/fail2ban/config_template.j2
    dest: "/etc/fail2ban/filter.d/{{ fail2ban_item['name'] }}.conf"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ fail2ban_filters_custom }}"
  loop_control:
    loop_var: fail2ban_item
  notify: restart fail2ban


- name: download /etc/fail2ban/filter.d/ configs
  get_url:
    url: "{{ fail2ban_filter_url['url'] }}"
    dest: "/etc/fail2ban/filter.d/{{ fail2ban_filter_url['name'] }}.conf"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ fail2ban_filters_download }}"
  loop_control:
    loop_var: fail2ban_filter_url
  notify: restart fail2ban
